# 権限修正版のワークフロー
# .github/workflows/daily_prediction.yml

name: Daily Pachislot Prediction

on:
  schedule:
    # 日本時間 毎朝6:00 (UTC 21:00)
    - cron: '0 21 * * *'
  workflow_dispatch:  # 手動実行も可能

# 権限を明示的に設定
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  predict:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Cache pip packages
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
    
    - name: Install dependencies
      run: |
        pip install torch --index-url https://download.pytorch.org/whl/cpu
        pip install pandas numpy scikit-learn beautifulsoup4 requests joblib
    
    - name: Download model from releases
      run: |
        # モデルとスケーラーをGitHub Releasesから取得
        wget https://github.com/halc8312/slot_obu/releases/download/quantile-model-v1/quantile_loss_model.pth || echo "Model not found"
        wget https://github.com/halc8312/slot_obu/releases/download/quantile-model-v1/quantile_feature_scaler.joblib || echo "Scaler not found"
        # データファイル（オプション）
        wget https://github.com/halc8312/slot_obu/releases/download/quantile-model-v1/final_integrated_13months_data.csv || echo "Data file not found"
    
    - name: Collect daily data
      run: python scripts/daily_data_collector.py
    
    - name: Run prediction
      run: python scripts/daily_predictor.py
    
    - name: Generate report
      run: python scripts/report_generator.py
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reports
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: prediction-results
        path: |
          reports/*.html
          data/*.csv
        retention-days: 30